# 운동 데이터베이스 - 아파트 커뮤니티 헬스장 + 집 기구 기준

EXERCISES = {
    "워밍업 (어깨 필수)": [
        {
            "id": "arm_circle",
            "name": "암 서클",
            "equipment": "맨몸",
            "muscles": "어깨 전체 가동성",
            "how_to": "팔을 크게 앞뒤로 10~15회씩 천천히 돌립니다. 통증이 없는 범위만 사용하세요.",
            "tip": "본 운동 전 반드시 하세요. 회전근개 이력에는 워밍업이 핵심입니다.",
            "shoulder_safe": True,
        },
        {
            "id": "scapular_pushup",
            "name": "스캡ular 푸쉬업",
            "equipment": "맨몸 / 푸쉬업 바",
            "muscles": "전거근, 견갑골 안정",
            "how_to": "플랭크 자세에서 팔꿈치는 펴고, 어깨뼈만 모았다 벌렸다 합니다. 몸통은 움직이지 마세요.",
            "tip": "어깨가 안정돼야 프레스가 안전합니다. 10~15회 2세트.",
            "shoulder_safe": True,
        },
        {
            "id": "band_er",
            "name": "밴드 외회전",
            "equipment": "밴드 (없으면 맨손으로 천천히)",
            "muscles": "회전근개 (가시아래근)",
            "how_to": "팔꿈치를 옆구리에 붙이고 90도 유지. 손등을 바깥으로 천천히 돌립니다.",
            "tip": "가벼운 저항으로 15회 2세트. 본 운동 전에 필수.",
            "shoulder_safe": True,
        },
        {
            "id": "face_pull_wu",
            "name": "페이스 풀 (워밍업)",
            "equipment": "케이블 / 밴드",
            "muscles": "후면 삼각근, 회전근개",
            "how_to": "로프를 얼굴 쪽으로 당기며 팔꿈치를 높이고 외회전합니다.",
            "tip": "가벼운 무게로 15회. 어깨 건강 유지용으로 거의 매일 해도 됩니다.",
            "shoulder_safe": True,
        },
    ],
    "하체": [
        {
            "id": "leg_press",
            "name": "레그프레스",
            "equipment": "레그프레스 머신",
            "muscles": "대퇴사두근, 둔근, 햄스트링",
            "how_to": "허리를 패드에 밀착하세요. 발은 어깨너비, 무릎은 발끝 방향. 내릴 때 약 90도, 올릴 때 무릎을 완전히 잠그지 마세요.",
            "tip": "발 위치를 높게 두면 둔근·햄스트링, 낮게 두면 앞허벅지 자극이 커집니다.",
            "shoulder_safe": True,
        },
        {
            "id": "squat_machine",
            "name": "스쿼트 (머신/스미스)",
            "equipment": "스쿼트 머신 / 스미스 머신",
            "muscles": "대퇴사두근, 둔근, 코어",
            "how_to": "발은 어깨너비, 발끝은 약간 바깥. 엉덩이를 뒤로 빼며 내려가고 무릎이 발끝 방향을 유지하세요.",
            "tip": "코어에 힘을 주고 시선은 앞. 깊이보다 허리가 둥글어지지 않는 게 우선입니다.",
            "shoulder_safe": True,
        },
        {
            "id": "rdl",
            "name": "루마니안 데드리프트",
            "equipment": "데드리프트 바 / 스미스 / 덤벨",
            "muscles": "햄스트링, 둔근, 척추기립근",
            "how_to": "무릎은 살짝만 굽히고 엉덩이를 뒤로 밀며 상체를 숙입니다. 허리는 절대 둥글게 말지 마세요.",
            "tip": "바가 다리에 거의 붙어서 내려가게 하세요. 햄스트링이 늘어나는 느낌이 맞습니다.",
            "shoulder_safe": True,
        },
        {
            "id": "leg_extension",
            "name": "레그 익스텐션",
            "equipment": "레그 익스텐션 머신",
            "muscles": "대퇴사두근 (앞허벅지)",
            "how_to": "무릎을 펴면서 올리되 완전히 잠그지 말고 정점에서 1초. 내릴 때는 천천히.",
            "tip": "반동 없이. 너무 무거우면 무릎에 부담이 갑니다.",
            "shoulder_safe": True,
        },
        {
            "id": "leg_curl",
            "name": "레그 컬",
            "equipment": "레그 컬 머신 (허벅지 뒤 당기는 머신)",
            "muscles": "햄스트링 (뒷허벅지)",
            "how_to": "엉덩이가 들리지 않게 밀착. 발꿈치를 엉덩이 쪽으로 당긴다는 느낌으로 굽히세요.",
            "tip": "앞허벅지 운동만 하면 불균형이 생깁니다. 컬을 꼭 넣으세요.",
            "shoulder_safe": True,
        },
        {
            "id": "dumbbell_lunge",
            "name": "덤벨 런지",
            "equipment": "덤벨",
            "muscles": "대퇴사두근, 둔근, 코어",
            "how_to": "한 발을 크게 내딛고 뒷무릎이 바닥에 거의 닿을 때까지. 앞무릎이 발끝 앞으로 과하게 나가지 않게.",
            "tip": "상체를 세우고 앞발 뒤꿈치로 밀어 올라오세요.",
            "shoulder_safe": True,
        },
        {
            "id": "calf_raise",
            "name": "카프 레이즈",
            "equipment": "스미스 / 레그프레스 / 맨몸",
            "muscles": "비복근, 가자미근 (종아리)",
            "how_to": "발끝으로 올라갔다가 발뒤꿈치가 충분히 내려오게 하세요. 정점에서 1초.",
            "tip": "종아리는 횟수를 많이 (12~20회) 하는 편이 잘 반응합니다.",
            "shoulder_safe": True,
        },
    ],
    "상체 밀기": [
        {
            "id": "bench_press",
            "name": "벤치프레스",
            "equipment": "벤치프레스 / 스미스 머신",
            "muscles": "대흉근, 삼두근, 전면 삼각근",
            "how_to": "견갑골을 모아 벤치에 고정. 바는 가슴 중앙에 터치. 팔꿈치는 몸통에서 약 45도.",
            "tip": "어깨가 귀 쪽으로 올라가면 위험합니다. 워밍업 세트 2개를 꼭 하세요.",
            "shoulder_safe": False,
        },
        {
            "id": "incline_dumbbell_press",
            "name": "인클라인 덤벨 프레스",
            "equipment": "덤벨 + 벤치",
            "muscles": "상부 대흉근, 전면 삼각근, 삼두",
            "how_to": "벤치 30~45도. 덤벨을 가슴 위쪽에서 위로. 어깨가 들리지 않게 견갑골 고정.",
            "tip": "플랫 벤치보다 어깨가 편할 수 있어 메인 가슴 운동으로 추천합니다.",
            "shoulder_safe": True,
        },
        {
            "id": "pec_deck",
            "name": "버터플라이 (펙덱)",
            "equipment": "버터플라이 머신",
            "muscles": "대흉근",
            "how_to": "팔꿈치를 살짝 굽힌 채 팔을 모읍니다. 정점에서 가슴을 쥐어짜고 천천히 벌리세요.",
            "tip": "프레스 후에 넣으면 가슴 자극을 마무리하기 좋습니다.",
            "shoulder_safe": True,
        },
        {
            "id": "shoulder_press_machine",
            "name": "숄더 프레스 머신",
            "equipment": "숄더 프레스 머신",
            "muscles": "삼각근, 삼두",
            "how_to": "등을 패드에 붙이고 머리 옆에서 위로 밉니다. 허리를 과하게 젖히지 마세요.",
            "tip": "통증 있으면 즉시 중단. 가동범위를 줄이거나 덤벨 라이트 프레스로 바꾸세요.",
            "shoulder_safe": False,
        },
        {
            "id": "ohp_machine",
            "name": "오버헤드 프레스 머신",
            "equipment": "어깨 위로 올리는 머신",
            "muscles": "삼각근, 삼두",
            "how_to": "손잡이를 귀 옆에서 시작해 위로. 어깨를 으쓱하지 말고 날개뼈를 내린 상태를 유지.",
            "tip": "회전근개 이력이 있으니 가벼운 무게 + 충분한 워밍업 후에만.",
            "shoulder_safe": False,
        },
        {
            "id": "lateral_raise",
            "name": "사이드 레터럴 레이즈",
            "equipment": "덤벨",
            "muscles": "측면 삼각근",
            "how_to": "팔꿈치 살짝 굽히고 옆으로 어깨 높이까지만. 새끼손가락이 약간 위를 향하게.",
            "tip": "무거운 덤벨로 던지듯 올리면 승모근만 씁니다. 가벼운 무게가 맞습니다.",
            "shoulder_safe": True,
        },
        {
            "id": "dips",
            "name": "딥스",
            "equipment": "풀업딥스바",
            "muscles": "삼두근, 하부 대흉근",
            "how_to": "상체를 살짝 숙이면 가슴, 세우면 삼두. 너무 깊이 내려가지 마세요.",
            "tip": "어깨 앞쪽이 찌르면 중단하고 푸쉬업으로 대체하세요.",
            "shoulder_safe": False,
        },
        {
            "id": "pushup",
            "name": "푸쉬업",
            "equipment": "푸쉬업 바 / 맨몸",
            "muscles": "대흉근, 삼두, 코어",
            "how_to": "손은 어깨보다 약간 넓게. 몸 일직선. 가슴이 바에 가까워질 때까지.",
            "tip": "집에서도 가능. 무릎 푸쉬업으로 시작해도 됩니다.",
            "shoulder_safe": True,
        },
    ],
    "상체 당기기": [
        {
            "id": "lat_pulldown",
            "name": "랫풀다운",
            "equipment": "랫풀다운 머신",
            "muscles": "광배근, 이두근, 후면 삼각근",
            "how_to": "가슴을 열고 어깨를 내린 뒤, 팔꿈치로 당긴다는 느낌으로 바를 쇄골~턱 아래까지.",
            "tip": "상체를 과하게 뒤로 젖히면 등보다 팔만 씁니다.",
            "shoulder_safe": True,
        },
        {
            "id": "pullup",
            "name": "풀업 / 친업",
            "equipment": "풀업 바 (헬스장/집)",
            "muscles": "광배근, 이두근, 코어",
            "how_to": "어깨를 내리고 시작. 가슴을 바 쪽으로. 내려갈 때 통제하세요.",
            "tip": "1개도 안 되면 랫풀다운과 점프 풀업으로 쌓으세요.",
            "shoulder_safe": True,
        },
        {
            "id": "seated_row",
            "name": "시티드 로우 (로잉)",
            "equipment": "로잉/조정 머신",
            "muscles": "광배근, 중간 등, 후면 어깨",
            "how_to": "가슴을 내밀고 팔꿈치를 몸통 옆으로 당기며 견갑골을 모으세요.",
            "tip": "허리로 당기지 말고 등으로 당기세요.",
            "shoulder_safe": True,
        },
        {
            "id": "dumbbell_row",
            "name": "덤벨 로우",
            "equipment": "덤벨 + 벤치",
            "muscles": "광배근, 후면 삼각근",
            "how_to": "한 손을 벤치에 지지. 상체 거의 평행. 팔꿈치를 천장 쪽으로 당깁니다.",
            "tip": "몸통이 돌아가면 무게가 큰 겁니다. 줄이세요.",
            "shoulder_safe": True,
        },
        {
            "id": "face_pull",
            "name": "페이스 풀",
            "equipment": "케이블 / 밴드",
            "muscles": "후면 삼각근, 회전근개, 중간 승모",
            "how_to": "얼굴을 향해 당기면서 외회전. 팔꿈치가 손보다 높아야 합니다.",
            "tip": "어깨 이력 있으면 당기는 날마다 넣는 것을 추천합니다.",
            "shoulder_safe": True,
        },
        {
            "id": "bicep_curl",
            "name": "이두 컬",
            "equipment": "이두 머신 / 덤벨",
            "muscles": "이두근",
            "how_to": "팔꿈치를 옆구리에 고정. 반동 없이 올리고 내릴 때 긴장을 유지.",
            "tip": "무거운 컬은 어깨 앞쪽에 부담을 줄 수 있습니다.",
            "shoulder_safe": True,
        },
    ],
    "유산소": [
        {
            "id": "treadmill_walk",
            "name": "트레드밀 경사 걷기",
            "equipment": "트레드밀",
            "muscles": "하체, 둔근, 심폐",
            "how_to": "속도 4.5~6km/h, 경사 5~10%로 15~25분. 대화가 가능한 정도가 좋습니다.",
            "tip": "체지방 빼는 용도로 가장 부담이 적습니다. 무릎이 편합니다.",
            "shoulder_safe": True,
        },
        {
            "id": "treadmill",
            "name": "트레드밀 가벼운 조깅",
            "equipment": "트레드밀",
            "muscles": "하체 전체, 심폐",
            "how_to": "숨이 차되 대화는 가능한 속도로 10~20분.",
            "tip": "하체 운동한 날은 조깅보다 걷기가 회복에 낫습니다.",
            "shoulder_safe": True,
        },
        {
            "id": "stair_climber",
            "name": "천국의 계단",
            "equipment": "스텝퍼",
            "muscles": "둔근, 하체, 심폐",
            "how_to": "상체를 세우고 손 힘이 아니라 다리로 밀어 올라가세요. 10~15분.",
            "tip": "무릎이 불편하면 속도를 낮추거나 트레드밀 경사 걷기로 바꾸세요.",
            "shoulder_safe": True,
        },
        {
            "id": "rowing",
            "name": "로잉 머신",
            "equipment": "로잉(조정) 머신",
            "muscles": "등, 하체, 코어, 심폐",
            "how_to": "다리 → 상체 → 팔 순서로 당기고, 돌아올 때는 팔 → 상체 → 다리. 8~15분.",
            "tip": "전신 + 유산소라 시간이 없을 때 효율이 좋습니다.",
            "shoulder_safe": True,
        },
    ],
    "코어 & 홈트": [
        {
            "id": "plank",
            "name": "플랭크",
            "equipment": "맨몸",
            "muscles": "코어 전체",
            "how_to": "팔꿈치와 발끝으로 지탱. 엉덩이가 처지거나 너무 올라가지 않게 일직선.",
            "tip": "호흡을 멈추지 마세요. 30초부터 시작해 60초를 목표.",
            "shoulder_safe": True,
        },
        {
            "id": "dead_bug",
            "name": "데드버그",
            "equipment": "맨몸",
            "muscles": "코어 안정성",
            "how_to": "누워서 반대쪽 팔·다리를 천천히 뻗었다가 복귀. 허리가 바닥에 붙어 있게.",
            "tip": "허리 부담이 적은 코어 운동입니다.",
            "shoulder_safe": True,
        },
    ],
}

RECOMMENDED = {
    0: {  # Monday
        "title": "하체 + 코어",
        "warmup": ["arm_circle", "scapular_pushup"],
        "main": ["leg_press", "rdl", "leg_curl", "leg_extension", "dumbbell_lunge", "plank"],
        "cardio": ["treadmill_walk", "stair_climber", "rowing"],
    },
    1: {
        "title": "휴식 또는 가벼운 유산소",
        "warmup": [],
        "main": [],
        "cardio": ["treadmill_walk", "treadmill", "stair_climber", "rowing"],
    },
    2: {  # Wednesday
        "title": "상체 밀기 (가슴·어깨·삼두)",
        "warmup": ["arm_circle", "scapular_pushup", "band_er", "face_pull_wu"],
        "main": ["incline_dumbbell_press", "pec_deck", "shoulder_press_machine", "lateral_raise", "pushup"],
        "cardio": ["treadmill_walk", "treadmill", "stair_climber", "rowing"],
    },
    3: {
        "title": "휴식 또는 가벼운 유산소",
        "warmup": [],
        "main": [],
        "cardio": ["treadmill_walk", "treadmill", "stair_climber", "rowing"],
    },
    4: {  # Friday
        "title": "상체 당기기 (등·이두) + 코어",
        "warmup": ["arm_circle", "face_pull_wu"],
        "main": ["lat_pulldown", "pullup", "seated_row", "face_pull", "bicep_curl", "dead_bug"],
        "cardio": ["treadmill_walk", "stair_climber", "rowing"],
    },
    5: {
        "title": "선택: 전신 / 약한 부위",
        "warmup": ["arm_circle", "scapular_pushup"],
        "main": ["squat_machine", "dumbbell_row", "pushup", "plank"],
        "cardio": ["treadmill_walk", "stair_climber", "rowing"],
    },
    6: {
        "title": "완전 휴식",
        "warmup": [],
        "main": [],
        "cardio": [],
    },
}


def get_all_exercises():
    all_ex = []
    for category, items in EXERCISES.items():
        for ex in items:
            ex_copy = dict(ex)
            ex_copy["category"] = category
            all_ex.append(ex_copy)
    return all_ex


def get_exercise_by_id(ex_id):
    for ex in get_all_exercises():
        if ex["id"] == ex_id:
            return ex
    return None
